export const timeline = [
  {
    company: "OpenClassrooms",
    title: "Concepteurs d'applications JS React",
    date: "2024 - 2025",
    description: "Formation diplômante de Concepteur d'application JS React",
    responsibilities: [
      "Développement de nouvelles fonctionnalités pour améliorer l'expérience utilisateur",
  "Implémentation d'un algorithme de recommandation pour suggérer des produits pertinents",
  "Optimisation du processus de paiement pour le rendre plus intuitif et convivial",
  "Création d'une fonctionnalité permettant le suivi des colis en temps réel",
    ],
  },
  {
    company: "BTH",
    title: "Commercial VRP",
    date: "2022 - 2024",
    description: "Conseiller technico-commercial",
    responsibilities: [
      "Prospection et acquisition de nouveaux clients pour les services d'isolation et de traitement de charpente",
  "Négociation et signature de contrats avec des particuliers et des professionnels",
  "Analyse des besoins des clients pour proposer des solutions adaptées",
  "Suivi des ventes et fidélisation de la clientèle existante",
  "Atteinte des objectifs commerciaux grâce à une excellente maîtrise des techniques de vente",
    ],
  },
  {
    company: "Butterfly Conciergerie",
    title: "PDG",
    date: "2018 - 2022",
    description: "Gestion d'une conciergerie",
    responsibilities: [
    "Gestion opérationnelle de l'entreprise, incluant la supervision de trois employés",
  "Gestion des relations clients et des appartements en location sur Airbnb",
  "Mise en place de stratégies pour optimiser les services de conciergerie et améliorer l'expérience client",
  "Développement de partenariats stratégiques avec des propriétaires et des prestataires locaux",
  "Suivi des performances financières et gestion des objectifs de rentabilité",
    ],
  },
  {
    company: "Richemont Meyrin (CH)",
    title: "Steward de réception",
    date: "2015 - 2018",
    description: "Assurer une expérience client premium dans un environnement de luxe",
    responsibilities: [
  "Accueil et gestion des visiteurs dans un cadre prestigieux",
    "Supervision des entrées et sorties lors des événements de vente de montres de luxe",
    "Garantir la sécurité et la confidentialité des opérations sur site",
    "Coordination avec les équipes internes pour une expérience client fluide et irréprochable",
    "Mise en œuvre des standards d'excellence et de service propres à l'univers du luxe",
    ],
  },
  {
    company: "Police Nationale",
    title: "Adjoint de sécurité",
    date: "2009 - 2015",
    description: "Assurer la sécurité et le maintien de l'ordre public",
    responsibilities: [
      "Assistance aux missions de sécurisation et de prévention en collaboration avec les forces de l'ordre",
    "Patrouilles à pied ou en véhicule pour garantir la sécurité des citoyens",
    "Gestion de l'accueil et de l'orientation du public dans les commissariats",
    "Participation à des opérations de surveillance et de contrôle",
    "Contribution à la rédaction de rapports et comptes rendus opérationnels",
    ],
  },
];
